name: multi_stream_controller
description: A way to easily pipe your streams into one controller
version: 0.0.1
homepage: https://github.com/Sach97/multi_stream_controller
author: Sacha Arbonel <sacha.arbonel@hotmail.fr>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  stream_channel: ^1.6.8


dev_dependencies:
  test: ^1.0.0
